#!/usr/bin/env bash
# render-audit.sh — projects the orchestrator's own journal into a human-readable audit.md.
#
# audit.md is generated, never hand-authored: this script deterministically OVERWRITES it in full
# from `.doflow/state/orchestration/<slug>.json`'s `history[]` array (WorkflowOrchestrator's own
# journal — the single source of truth for stage/gate handoffs), one markdown table row per
# entry. It never appends across runs and never reads the previous audit.md — a stale row can
# only come from a stale journal, never from this script's own accumulation.
#
# Fail-open, matching validate-artifacts.sh's own convention: no active feature, no resolver, or
# no orchestration run recorded yet are all reported via a note and exit 0 — never a hard error,
# and no audit.md is written when there is nothing to render.
#
# Usage: render-audit.sh [--slug=<slug>] [--json]
#   No --slug → resolve the active feature via do-paths.sh, exactly like validate-artifacts.sh.

set -uo pipefail

emit_json=false
slug_override=""
bad_args=()
for a in "$@"; do
  case "$a" in
    --json)   emit_json=true ;;
    --slug=*) slug_override="${a#--slug=}" ;;
    *) bad_args+=("$a") ;;
  esac
done
# An unrecognized argument previously fell through silently — including the space-separated
# `--slug value` form (only `--slug=value` is accepted), which meant a typo rendered the ACTIVE
# feature's audit.md instead of the one the caller named, with no signal that anything went wrong.
if [ "${#bad_args[@]}" -gt 0 ]; then
  if [ "$emit_json" = true ]; then
    printf '{"ok":false,"error":"unrecognized-argument","args":"%s"}\n' "${bad_args[*]}" >&2
  else
    printf 'render-audit: unrecognized argument(s): %s (use --slug=<value>, not --slug <value>)\n' "${bad_args[*]}" >&2
  fi
  exit 2
fi

note() {
  if [ "$emit_json" = true ]; then
    printf '{"ok":true,"note":"%s","written":false}\n' "$1"
  else
    printf 'render-audit: %s (audit.md not written)\n' "$1"
  fi
  exit 0
}

command -v jq >/dev/null 2>&1 || note "jq-absent"

script_dir="$(cd "$(dirname "$0")" && pwd)"
RESOLVER="$script_dir/do-paths.sh"
[ -f "$RESOLVER" ] || RESOLVER="${DOFLOW_CONFIG_DIR:+$DOFLOW_CONFIG_DIR/scripts/doflow/bash/do-paths.sh}"
[ -f "$RESOLVER" ] || note "resolver-absent"

resolver_args=(--json)
[ -n "$slug_override" ] && resolver_args+=("--slug=$slug_override")
resolved_json=$(bash "$RESOLVER" "${resolver_args[@]}" 2>/dev/null) || note "resolver-error"

repo_root=$(printf '%s' "$resolved_json" | jq -r '.repo_root // empty')
feature_dir=$(printf '%s' "$resolved_json" | jq -r '.feature_dir // empty')
feature_slug=$(printf '%s' "$resolved_json" | jq -r '.feature_slug // empty')
[ -n "$feature_slug" ] || note "no-active-feature"

# WorkflowOrchestrator's own stateDir/runFile convention (workflow-orchestrator.js):
#   stateDir = <root>/.doflow/state/orchestration ; runFile = <stateDir>/<taskId>.json
journal_file="$repo_root/.doflow/state/orchestration/$feature_slug.json"
[ -f "$journal_file" ] || note "no orchestration run recorded yet"

jq -e '.history | type == "array"' "$journal_file" >/dev/null 2>&1 || note "journal-unreadable"

audit_file="$repo_root/$feature_dir/audit.md"

# Render to a temp file first, then move it into place. `>"$audit_file"` truncates the target
# before the group runs, and with no `-e` a mid-stream jq abort (a malformed or hand-corrupted
# journal field) would otherwise leave a header-only audit.md behind while this script still
# reported written:true. Same fail-open philosophy as the notes above: report a clear failure
# rather than corrupt the target.
tmp_audit="$(mktemp "${audit_file}.XXXXXX" 2>/dev/null || mktemp)"

{
  printf '# Audit Trail: %s\n\n' "$feature_slug"
  printf '> Generated by `render-audit.sh` from `.doflow/state/orchestration/%s.json`. Do not\n' "$feature_slug"
  printf '> hand-edit — this file is fully regenerated from the orchestration journal on every run.\n\n'
  printf '| Date | Stage/Gate | Action | Note / Reason | Flags |\n'
  printf '|---|---|---|---|---|\n'
  jq -r '
    def esc: if . == null then "" else (tostring | gsub("\\\\"; "\\\\") | gsub("\\|"; "\\|") | gsub("\r\n|\n|\r"; " ")) end;
    .history[] |
    (.node // "—") as $stage |
    (if .action == "decide-gate" and (.detail != null and .detail != "")
       then .action + " (" + .detail + ")"
       else .action end) as $action |
    ((.note // "") | esc) as $note_raw |
    ((.detail // "") | esc) as $detail_raw |
    (if $note_raw != "" then $note_raw
     elif .action == "start" and $detail_raw != "" then $detail_raw
     else "—" end) as $note |
    (if .forced == true then "⚠ FORCED"
     elif .backfilled == true then "⚡ BACKFILLED"
     else "" end) as $flags |
    "| " + (.at | esc) + " | " + ($stage | esc) + " | " + ($action | esc) + " | " + $note + " | " + $flags + " |"
  ' "$journal_file"
} >"$tmp_audit"
rc=$?
if [ "$rc" -ne 0 ] || [ ! -s "$tmp_audit" ]; then
  rm -f "$tmp_audit"
  if [ "$emit_json" = true ]; then
    printf '{"ok":false,"error":"render-failed","path":"%s"}\n' "$feature_dir/audit.md" >&2
  else
    printf 'render-audit: failed to render %s (journal may be malformed)\n' "$feature_dir/audit.md" >&2
  fi
  exit 1
fi
chmod 644 "$tmp_audit" 2>/dev/null || true
# Unchecked, an mv failure (target dir missing — do-brainstorm's own state before its step 4
# mkdir, say — or a permissions problem) left the rendered content stranded in $tmp_audit while
# this script still reported written:true and exit 0: a false success from the one tool whose job
# is a trustworthy provenance record.
mv_err="$(mv "$tmp_audit" "$audit_file" 2>&1)"
mv_rc=$?
if [ "$mv_rc" -ne 0 ]; then
  rm -f "$tmp_audit"
  if [ "$emit_json" = true ]; then
    printf '{"ok":false,"error":"move-failed","path":"%s"}\n' "$feature_dir/audit.md" >&2
  else
    printf 'render-audit: failed to write %s (%s)\n' "$feature_dir/audit.md" "$mv_err" >&2
  fi
  exit 1
fi

if [ "$emit_json" = true ]; then
  printf '{"ok":true,"written":true,"path":"%s"}\n' "$feature_dir/audit.md"
else
  printf 'render-audit: wrote %s\n' "$feature_dir/audit.md"
fi
exit 0
